global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'localhost:8080','localhost:8082','localhost:7070' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'localhost:9100', 'localhost:9101' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]