global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]

  - job_name: 'session-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7070' ]

  - job_name: 'user-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7071' ]

  - job_name: 'image-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7074' ]

  - job_name: 'hotels-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7075' ]

  - job_name: 'comments-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7078' ]