global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'node_exporter:9101', 'localhost:9100' ]

  - job_name: 'session-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7070', 'localhost:7070', '0.0.0.0:7070' ]

  - job_name: 'user-microservice'
    static_configs:
      - targets: [ 'host.docker.internal:7071', 'localhost:7071', '0.0.0.0:7071' ]