grpc:
  Port: ":8079"
  CookieLifeTime: 44640
  CsrfExpire: 15
  SessionID: "SessionID"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

metrics:
  Url: 0.0.0.0:7070
  ServiceName: auth_microservice

jaeger:
  Host: localhost:6831
  ServiceName: Sessions_GRPC
  LogSpans: false